name: pandemonium2020
description: A new Flutter project.

version: 1.5.2

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  sqflite: ^2.0.2
  path_provider: ^2.0.9
  firebase_core: ^1.12.0
  firebase_analytics: ^9.1.0
  cloud_firestore: ^3.1.8
  firebase_admob: ^0.11.2
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/city.jpeg
    - assets/tutorial/tut1.gif
    - assets/tutorial/tut2.gif
    - assets/tutorial/tut3.gif
    - assets/tutorial/tut4.gif
    - assets/tutorial/tut5.gif
    - assets/tutorial/tut6.gif
