name: pandemonium2020
description: A new Flutter project.

version: 1.5.2

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  sqflite: ^1.3.0+1
  path_provider: ^1.6.7
  firebase_core: ^0.5.0+1
  firebase_analytics: ^5.0.2
  cloud_firestore: ^0.14.1
  firebase_admob: ^0.10.0+2
  carousel_slider: ^2.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icons/icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/images/city.jpeg
    - assets/tutorial/tut1.gif
    - assets/tutorial/tut2.gif
    - assets/tutorial/tut3.gif
    - assets/tutorial/tut4.gif
    - assets/tutorial/tut5.gif
    - assets/tutorial/tut6.gif
